# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentApp', '0001_initial'),
        ('complianceAuditApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlassessment',
            name='assessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='control_assessments', to='complianceAuditApp.complianceaudit'),
        ),
        migrations.AddField(
            model_name='compliancestandard',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_standards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='audit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='complianceAuditApp.complianceaudit'),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='complianceAuditApp.compliancestandard'),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='compliance_audits', to='departmentApp.department'),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='lead_auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='related_incidents',
            field=models.ManyToManyField(blank=True, related_name='compliance_audits', to='incidentApp.incident'),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audits', to='complianceAuditApp.compliancestandard'),
        ),
        migrations.AddField(
            model_name='complianceaudit',
            name='triggered_by_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_audits', to='incidentApp.incident'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='complianceAuditApp.complianceaudit'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='related_incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='incidentApp.incident'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['audit', 'status'], name='complianceA_audit_i_a041e3_idx'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['status', 'remediation_required'], name='complianceA_status_ba48a4_idx'),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['control_id'], name='complianceA_control_00e72a_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancestandard',
            index=models.Index(fields=['standard_type', 'is_active'], name='complianceA_standar_22b5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancestandard',
            index=models.Index(fields=['is_active'], name='complianceA_is_acti_e7c5c6_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['status', 'planned_start_date'], name='complianceA_status_9f5614_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['audit_type', 'status'], name='complianceA_audit_t_7ed872_idx'),
        ),
        migrations.AddIndex(
            model_name='complianceaudit',
            index=models.Index(fields=['standard', 'status'], name='complianceA_standar_a63881_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['status', 'risk_level'], name='complianceA_status_cd496f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['audit', 'status'], name='complianceA_audit_i_8a24d1_idx'),
        ),
    ]
