# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(editable=False, help_text='System-generated incident number', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Brief title describing the incident', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('investigating', 'Investigating'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='pending', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('risk_score', models.IntegerField(default=0, help_text='Risk score (0-100)')),
                ('danger_zone', models.BooleanField(default=True, help_text='Whether this incident is in the danger zone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on how the incident was resolved', null=True)),
                ('sla_due_date', models.DateTimeField(blank=True, help_text='Due date based on SLA (must be set manually)', null=True)),
                ('sla_violated', models.BooleanField(default=False, help_text='Whether SLA was violated')),
                ('escalation_reason', models.TextField(blank=True, help_text='Reason for escalating the incident', null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Whether this is an internal note (not visible to all)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('security', 'Security Report'), ('compliance', 'Compliance Report'), ('access_control', 'Access Control Report'), ('incident', 'Incident Report'), ('user_activity', 'User Activity Report'), ('ai_analytics', 'AI Analytics Report'), ('custom', 'Custom Report')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('file_path', models.CharField(blank=True, help_text='Relative path to report file from MEDIA_ROOT', max_length=500, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters used to generate this report')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the report (email status, etc.)')),
                ('is_scheduled', models.BooleanField(default=False)),
                ('schedule_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether this report is publicly accessible')),
                ('download_count', models.IntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('security', 'Security Report'), ('compliance', 'Compliance Report'), ('access_control', 'Access Control Report'), ('incident', 'Incident Report'), ('user_activity', 'User Activity Report'), ('ai_analytics', 'AI Analytics Report'), ('custom', 'Custom Report')], max_length=20)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, help_text='Cron expression for custom schedules', max_length=100, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict, help_text='Parameters for report generation')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('additional_emails', models.TextField(blank=True, help_text='Comma-separated list of additional email addresses', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_run'],
            },
        ),
    ]
