# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingApp', '0001_initial'),
        ('learningProgressApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecompletion',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.module'),
        ),
        migrations.AddField(
            model_name='materialprogress',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.trainingmaterial'),
        ),
        migrations.AddField(
            model_name='materialprogress',
            name='module_completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_progress', to='learningProgressApp.modulecompletion'),
        ),
    ]
