# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learningProgressApp', '0002_initial'),
        ('trainingApp', '0001_initial'),
        ('trainingCandidateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningsession',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_sessions', to='trainingCandidateApp.candidate'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.module'),
        ),
        migrations.AddField(
            model_name='learningsession',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='trainingCandidateApp.candidate'),
        ),
        migrations.AddField(
            model_name='learningprogress',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AddField(
            model_name='learningachievement',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='trainingCandidateApp.candidate'),
        ),
        migrations.AddField(
            model_name='learningachievement',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AlterUniqueTogether(
            name='modulecompletion',
            unique_together={('learning_progress', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='materialprogress',
            unique_together={('module_completion', 'material')},
        ),
        migrations.AlterUniqueTogether(
            name='learningprogress',
            unique_together={('candidate', 'training')},
        ),
        migrations.AlterUniqueTogether(
            name='learningachievement',
            unique_together={('candidate', 'achievement_type', 'training')},
        ),
    ]
