# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('finding_type', models.CharField(choices=[('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation'), ('incident_related', 'Incident-Related')], default='minor', max_length=50)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('remediation_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('external', 'External Audit'), ('regulatory', 'Regulatory Audit'), ('certification', 'Certification Audit'), ('incident_response', 'Incident Response Audit')], default='internal', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('controls_assessed', models.IntegerField(default=0)),
                ('compliance_rate', models.FloatField(blank=True, null=True)),
                ('risk_score_from_incident', models.FloatField(blank=True, null=True)),
                ('incident_severity_match', models.BooleanField(default=False)),
                ('total_findings', models.IntegerField(default=0)),
                ('open_findings', models.IntegerField(default=0)),
                ('critical_findings', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('report_type', models.CharField(choices=[('audit_report', 'Audit Report'), ('compliance_summary', 'Compliance Summary'), ('gap_analysis', 'Gap Analysis'), ('finding_summary', 'Finding Summary'), ('control_assessment', 'Control Assessment')], max_length=50)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('html', 'HTML')], max_length=10)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='compliance_reports/')),
                ('file_content', models.TextField(blank=True, null=True)),
                ('parameters', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('standard_type', models.CharField(choices=[('gdpr', 'GDPR'), ('iso27001', 'ISO 27001'), ('soc2', 'SOC 2'), ('hipaa', 'HIPAA'), ('pci_dss', 'PCI DSS'), ('rwanda_dpa', 'Rwanda Data Protection Act'), ('nist', 'NIST Cybersecurity Framework'), ('custom', 'Custom Standard')], max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('total_controls', models.IntegerField(default=0)),
                ('mandatory_controls', models.IntegerField(default=0)),
                ('control_counter', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('control_name', models.CharField(max_length=500)),
                ('control_description', models.TextField()),
                ('control_category', models.CharField(blank=True, help_text='e.g., Access Control, Data Protection, Network Security', max_length=100, null=True)),
                ('status', models.CharField(choices=[('not_assessed', 'Not Assessed'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant'), ('partially_compliant', 'Partially Compliant'), ('not_applicable', 'Not Applicable')], default='not_assessed', max_length=50)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('remediation_required', models.BooleanField(default=False)),
                ('remediation_status', models.CharField(choices=[('not_required', 'Not Required'), ('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified')], default='not_required', max_length=50)),
                ('remediation_deadline', models.DateField(blank=True, null=True)),
                ('remediation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['control_id'],
            },
        ),
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField(unique=True)),
                ('total_audits', models.IntegerField(default=0)),
                ('completed_audits', models.IntegerField(default=0)),
                ('in_progress_audits', models.IntegerField(default=0)),
                ('incident_audits', models.IntegerField(default=0)),
                ('total_findings', models.IntegerField(default=0)),
                ('open_findings', models.IntegerField(default=0)),
                ('critical_findings', models.IntegerField(default=0)),
                ('overdue_findings', models.IntegerField(default=0)),
                ('total_controls_assessed', models.IntegerField(default=0)),
                ('compliant_controls', models.IntegerField(default=0)),
                ('total_standards', models.IntegerField(default=0)),
                ('active_standards', models.IntegerField(default=0)),
                ('overall_compliance_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-metric_date'],
            },
        ),
    ]
