# Generated by Django 4.2 on 2026-06-24 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complianceAuditApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditfinding',
            name='resolution_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='solved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='controlassessment',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_controls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditfinding',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('in_progress', 'In Progress'), ('solved', 'Solved'), ('closed', 'Closed')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='controlassessment',
            name='remediation_status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('not_required', 'Not Required')], default='waiting', max_length=50),
        ),
        migrations.AddIndex(
            model_name='controlassessment',
            index=models.Index(fields=['remediation_status'], name='complianceA_remedia_82d2b4_idx'),
        ),
    ]
