# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0002_initial'),
        ('incidentApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportschedule',
            name='recipients',
            field=models.ManyToManyField(help_text='Users who receive this scheduled report', related_name='scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', related_query_name='incident_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Users this report is shared with', related_name='shared_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidentApp.incident'),
        ),
        migrations.AddField(
            model_name='incidentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidentApp.incident'),
        ),
        migrations.AddField(
            model_name='incidentattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User assigned to handle this incident (manual assignment only)', limit_choices_to=models.Q(('role__in', ['admin', 'hr_manager', 'security_analyst', 'compliance_officer'])), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created/triggered this incident record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department related to this incident (auto-detected from user)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='departmentApp.department'),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalated_by',
            field=models.ForeignKey(blank=True, help_text='User who escalated the incident', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='log',
            field=models.ForeignKey(help_text='The log that triggered this incident', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='userApp.userlog'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['is_active'], name='incidentApp_is_acti_4f66c3_idx'),
        ),
        migrations.AddIndex(
            model_name='reportschedule',
            index=models.Index(fields=['next_run'], name='incidentApp_next_ru_e4a271_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_number'], name='incidentApp_report__b852de_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['report_type'], name='incidentApp_report__ebd435_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_by'], name='incidentApp_generat_06b28d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['generated_at'], name='incidentApp_generat_6f0131_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentcomment',
            index=models.Index(fields=['incident', 'created_at'], name='incidentApp_inciden_9c3d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['incident_number'], name='incidentApp_inciden_ccdb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidentApp_status_f30fc5_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['severity'], name='incidentApp_severit_a228fe_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['assigned_to'], name='incidentApp_assigne_f6dea9_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['danger_zone'], name='incidentApp_danger__eb75c0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='incidentApp_created_4dc15c_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['sla_due_date'], name='incidentApp_sla_due_506eb2_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['sla_violated'], name='incidentApp_sla_vio_198d9c_idx'),
        ),
    ]
