# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import userApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departmentApp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('work_mail_address', models.CharField(help_text='Work email address with custom domain format', max_length=255, unique=True, validators=[userApp.models.WorkEmailValidator()])),
                ('full_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr_manager', 'HR Manager'), ('compliance_officer', 'Compliance Officer'), ('security_analyst', 'Security Analyst'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('availability_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departmentApp.department')),
                ('departments', models.ManyToManyField(blank=True, related_name='security_analysts', to='departmentApp.department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, help_text="User's email at time of activity", max_length=255)),
                ('user_role', models.CharField(blank=True, help_text="User's role at time of activity", max_length=20, null=True)),
                ('log_type', models.CharField(choices=[('authentication', 'Authentication'), ('profile', 'Profile'), ('user_management', 'User Management'), ('department', 'Department Management'), ('system', 'System Activity')], db_index=True, max_length=20)),
                ('activity', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('login_otp_request', 'Login OTP Request'), ('login_otp_verify', 'Login OTP Verification'), ('register', 'User Registration'), ('profile_update', 'Profile Update'), ('password_change', 'Password Change'), ('password_reset_request', 'Password Reset Request'), ('password_reset_complete', 'Password Reset Complete'), ('user_create', 'Create User'), ('user_update', 'Update User'), ('user_delete', 'Delete User'), ('user_activate', 'Activate User'), ('user_deactivate', 'Deactivate User'), ('user_status_update', 'Update User Status'), ('department_create', 'Create Department'), ('department_update', 'Update Department'), ('department_delete', 'Delete Department'), ('contact_us', 'Contact Form Submission'), ('token_refresh', 'Token Refresh'), ('token_verify', 'Token Verification')], db_index=True, max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('request_data', models.JSONField(blank=True, help_text='Request data snapshot', null=True)),
                ('response_data', models.JSONField(blank=True, help_text='Response data snapshot', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device information', null=True)),
                ('endpoint', models.CharField(blank=True, help_text='API endpoint accessed', max_length=500, null=True)),
                ('http_method', models.CharField(blank=True, max_length=10, null=True)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code', null=True)),
                ('is_success', models.BooleanField(default=True, help_text='Whether the activity was successful')),
                ('is_auto_generated', models.BooleanField(default=False, help_text='System-generated log')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('duration', models.DurationField(blank=True, help_text='Activity duration in seconds', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_department', models.ForeignKey(blank=True, help_text='Department affected by this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, to='departmentApp.department')),
                ('target_user', models.ForeignKey(blank=True, help_text='User affected by this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='userApp_use_user_id_aa3f90_idx'), models.Index(fields=['activity', 'timestamp'], name='userApp_use_activit_07cb80_idx'), models.Index(fields=['log_type', 'timestamp'], name='userApp_use_log_typ_b3f258_idx'), models.Index(fields=['user_email', 'timestamp'], name='userApp_use_user_em_993a76_idx')],
            },
        ),
    ]
