# Generated by Django 4.2.28 on 2026-03-02 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainingApp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainingCandidateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='learner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidate',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.training'),
        ),
        migrations.AlterUniqueTogether(
            name='moduleprogress',
            unique_together={('candidate', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('learner', 'training')},
        ),
    ]
